### ISSUE TITLE
[ENHANCEMENT] -  Communicate that eating one fatty food will not cause instant fatness

### ISSUE THREAD

**Issue by asifexplore** [ShawnLemuelDabi/ITP-Group-18#19]
According to professors' criticism, the application needs to make it clear that consuming one fatty dish would not instantly make you overweight.

- [x] Display the message of "Will not cause instant fatness" onto the figma.

**Comment by ShawnLemuelDabi** [comment]
Added the below as per feedback

![image](https://user-images.githubusercontent.com/74093668/181154036-cbd23e1d-fdaa-4bc4-a508-87967227fdf3.png)


![image](https://user-images.githubusercontent.com/74093668/181154044-940b88dc-3fe3-4547-a910-ebe4a5c52af5.png)
