### ISSUE TITLE
Make mascot changes more visible

### ISSUE THREAD

**Issue by AfnanMuhd** [ShawnLemuelDabi/ITP-Group-18#20]

**Comment by ShawnLemuelDabi** [comment]
Thinking of adding GIFS to make the changes more "pop" in the figma. (Like how we get satisfying user feedback when we collect coins in a game)

**Comment by ShawnLemuelDabi** [comment]
Created a demo video

https://user-images.githubusercontent.com/74093668/181151120-6ee7546d-907a-4bbe-8981-5bc8c9a863f5.mp4
